config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resource :openbravo_settings
  end
end

app/controllers/admin/openbravo_settings_controller.rb
class Admin::OpenbravoSettingsController < Admin::BaseController

  def edit
    @organizations = Rails.cache.fetch('openbravo-organizations-list') do
      Openbravo::Organization.all.map{|org| [org.identifier, org.id] }
    end
    
    @tax_categories = Rails.cache.fetch('openbravo-tax-categories') do
      Openbravo::TaxCategory.all.map{|cat| [cat.name, cat.id] }
    end
    
    @tax_rates = Rails.cache.fetch('openbravo-tax-rates') do
      Openbravo::TaxRate.all.map{|tax| [tax.name, tax.id] }
    end
    
    @price_lists = Rails.cache.fetch('openbravo-price-lists') do
      Openbravo::PriceList.all.map{|list| [list.name, list.id] }
    end
    
    @bp_categories = Rails.cache.fetch('openbravo-bp-categories') do
      Openbravo::BusinessPartnerCategory.all.map{|cat| [cat.name, cat.id] }
    end
    
    @order_transaction_documents = Rails.cache.fetch('openbravo-order-transaction-documents') do
      Openbravo::DocumentType.all(:params => {:where => "documentCategory='SOO'"}).map{|doc| [doc.name, doc.id] }
    end
    
    @payment_terms = Openbravo::PaymentTerm.all.map{|term| [term.name, term.id] }
    @warehouses = Openbravo::Warehouse.all.map{|wh| [wh.name, wh.id]}
  end

  def update
    Spree::Openbravo::Config.set(params[:preferences])
    
    respond_to do |format|
      format.html {
        redirect_to admin_openbravo_settings_path
      }
    end
  end

end

app/views/admin/openbravo_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t('openbravo.settings') %></h1>

<%= form_tag(admin_openbravo_settings_path, :method => :put) do %>
  <p>
    <label><%= t("openbravo.url") %></label><br />
    <%= text_field_tag('preferences[url]', Spree::Openbravo::Config[:url]) %>
  </p>
  <p>
    <label><%= t('openbravo.organization') %></label><br />
    <%= select_tag('preferences[organization_id]', 
          options_for_select(@organizations, Spree::Openbravo::Config[:organization_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.tax_category') %></label><br />
    <%= select_tag('preferences[tax_category_id]', 
          options_for_select(@tax_categories, Spree::Openbravo::Config[:tax_category_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.tax_rate') %></label><br />
    <%= select_tag('preferences[tax_rate_id]', 
          options_for_select(@tax_rates, Spree::Openbravo::Config[:tax_rate_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.price_list') %></label><br />
    <%= select_tag('preferences[price_list_id]', 
          options_for_select(@price_lists, Spree::Openbravo::Config[:price_list_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.customer_category') %></label><br />
    <%= select_tag('preferences[customer_category_id]', 
          options_for_select(@bp_categories, Spree::Openbravo::Config[:customer_category_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.order_transaction_document') %></label><br />
    <%= select_tag('preferences[order_transaction_document_id]', 
          options_for_select(@order_transaction_documents, Spree::Openbravo::Config[:order_transaction_document_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.payment_term') %></label><br />
    <%= select_tag('preferences[payment_term_id]', 
          options_for_select(@payment_terms, Spree::Openbravo::Config[:payment_term_id])) %>
  </p>
  <p>
    <label><%= t('openbravo.warehouse') %></label><br />
    <%= select_tag('preferences[warehouse_id]', 
          options_for_select(@warehouses, Spree::Openbravo::Config[:warehouse_id])) %>
  </p>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_openbravo_settings_url %>
  </p>
<% end %>

app/views/admin/openbravo_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("openbravo.settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("openbravo.url") %>:</th>
    <td><%= Spree::Openbravo::Config[:url] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("openbravo.organization_id") %>:</th>
    <td><%= Spree::Openbravo::Config[:organization_id] %></td>
  </tr>
  <tr>
  <tr>
    <th scope="row"><%= t('openbravo.tax_category_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:tax_category_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.tax_rate_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:tax_rate_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.price_list_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:price_list_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.customer_category_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:customer_category_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.order_transaction_document_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:order_transaction_document_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.payment_term_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:payment_term_id] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('openbravo.warehouse_id') %>:</th>
    <td><%= Spree::Openbravo::Config[:warehouse_id] %></td>
  </tr>
</table>

<p><%= link_to_with_icon 'edit', t("edit"), edit_admin_openbravo_settings_path, :id => 'admin_openbravo_settings_link' %></p>